title:             Sonhos de menino
email:             moises@example.com
description:       As aventuras de Moises pelo Dundo
author:            Moises Nista Oscar
baseurl:           ""
url:               "http://sonhosdemenino.github.io"

# Social Profiles
twitter_username:
github_username:
facebook_username:

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
